### ISSUE TITLE
As a customer, I must be able to sign up so that I can request services in the city of my choice

### ISSUE THREAD

**Issue by CharanDhanireddy** [CharanDhanireddy/HandyConnect#1]
**Describe the solution you'd like**

- Details like user first name, last name, email address, city and address can be collected 
- Password security

**Corresponding user story**
- As a customer, I must be able to sign up  for the website.

**Additional context/details**
- Confirm password once more.

**Comment by srikanthraop** [comment]
#3 
Added bootstrap, routing and signup template.

**Comment by vdhavaleswarapu** [comment]
Frontend and backend development complete for the following features:
- Customer can sign up using their name, email, phone and their home-city
- Customer can login upon successful sign-up using the required credentials
- Error handling for incorrect password/username during login
