### ISSUE TITLE
As a user, I want to be able to login and view my data, bookings, and profile

### ISSUE THREAD

**Issue by CharanDhanireddy** [CharanDhanireddy/HandyConnect#5]
**Describe the solution you'd like**
- Login page for the website
- Email address and password for successful login

**Corresponding user story**
- As a user, I want to be able to login and view my data/bookings/profile

**Comment by vdhavaleswarapu** [comment]
Backend and frontend development complete for the following features:
- Customer can login to view their data (excluding the password) provided during signup
- Customer can view their bookings
- Vendor can login to view their data (excluding the password) provided during signup
- Vendor can view their bookings
