### ISSUE TITLE
As a user, I want to be able to select a city on logging in, so that I can see the services available in that city

### ISSUE THREAD

**Issue by CharanDhanireddy** [CharanDhanireddy/HandyConnect#6]
**Describe the solution you'd like**

- After login show a modal with a dropdown selector to select a city 

**Corresponding user story**
- As a user, I want to only see the services available in my city

**Additional context/details**
- After select city, must redirect to home

**Comment by vdhavaleswarapu** [comment]
Backend and frontend development for the following features complete:
- Customer can select a city upon logging in
- Customer gets a view of services available in the selected city
